### PR TITLE
CMake build files added.

### PR DESCRIPTION
**Pull request by cousinitt**
I added CMakeLists.txt files to allow folks to build using CMake. I also added CPack directives in the file to allow you to export built binaries (this was only tested on a Mac though).

I also added some missing documentation files? I found them helpful.

### CODE REVIEW

**Comment by dbetz** [comment]
I checked out your branch but I'm embarrassed to admit that I have no idea how to use cmake to build it. I tried just typing "cmake" in the root directory but only got the usage message. How do I build using cmake?

**Comment by cousinitt** [comment]
Ah - no sweat.
CMake is for building "out of source," amongst other things. For this
particular example, say we start in the xlisp directory:
cd ..
mkdir build
cd build
ccmake ../xlisp

So we have made a build directory outside of xlisp, so that the build
products don't get strewn all over our pristine source. The "ccmake"
command is a curses front end to CMake that I like. From there you can pick
the type of build, then type "g" for generate. This drops you out in a
shell prompt, where it has made makefiles for you (on other platforms,
you may have other types of build files generated). After that you can
make
make install
make clean
<etc>

With the CMake file I have in there, it also has a "package" target, which
will most likely build the source and then put it all in a tarred-gzip file
so that you can send it somewhere ... or you could alter the CMake file to
generate the target of your choice - RPM, DEB, etc.

Cheers,
Tim

**Comment by dbetz** [comment]
Thanks for the explanation of how to use cmake. I was able to follow them to build a working version of xlisp-repl. Could I ask you to take a few minutes to update the README.md file to include these instructions so that others who aren't familiar with cmake can build using your changes?

Thanks for your work on this!

David

**Comment by cousinitt** [comment]
You bet - I don't have a markdown viewer on this computer so I might do a couple of commits. Once I have it I'll post here.

**Comment by dbetz** [comment]
Thanks! I just merged it.

**Pull request merged**
