### PR TITLE
Wall compile cleanups

### PR DESCRIPTION
**Pull request by jordanlhenderson**
Cleanup code to suppress compiler warnings

### CODE REVIEW

**Comment by dbetz** [comment]
Please just make your own copy of this repository and rename it to something else. I no longer have time to work on this and will probably delete the repository soon. Sorry. I wrote this in 1983 and I think it's had a long enough run.

**Comment by jordanlhenderson** [comment]
Understood.  

Somewhere in the files, you've said that you want to be involved in releases and that we shouldn't distribute this code without coordination.  I can assume that's no longer true.

**Comment by dbetz** [comment]
I would like to know about what is being done with XLISP but you don't need to check with me for every change. However, please change the name and change the documentation to say something like "Based on XLISP by David Betz" so people don't think I'm still maintaining your releases. Good luck!

**Comment by jordanlhenderson** [comment]
Understood.  Will do.  I've been thinking of a lisp language for some of my projects and I've been frustrated with the incompatibility of Scheme system.  Scheme has always promised portability, but there's always niggling issues that require multiple releases of any project.  I'm impressed by the history of xlisp being used in the real world for real work and find it still builds in MSDOS (virtualized, but a limited 640K VM).  Thanks for the good work.

**Comment by dbetz** [comment]
I’m glad you find it useful.

**Comment by cousinitt** [comment]
Hi David - you can archive the repository, it is a visual indicator that
folks should probably fork it rather than sending pull requests. Here's a
blog article on how to do that:

https://github.blog/2017-11-08-archiving-repositories/

**Pull request closed without merging**
