### PR TITLE
Documentation moved to markdown format

### PR DESCRIPTION
**Pull request by DBJDBJ**
Also in a separate folder. This is done inside one-hour and very quickly checked. Please take over. Thanks.

### CODE REVIEW

**Review by cousinitt — APPROVED** [review]

**Comment by DBJDBJ** [comment]
Thanks @cousinitt , just please let someone quickly re-check the texts.

**Comment by DBJDBJ** [comment]
oops sorry, closed it before merge

**Comment by cousinitt** [comment]
Frankly, the MD docs are fantastic-looking.
The only issue that David might have is having his in-real-life contact info on GitHub.
(However, it is a good looking and accurate reproduction of the documents)

**Comment by DBJDBJ** [comment]
Thank's @cousinitt  Well yes, I thought the same, but I did as you have noticed.

IMHO, David deserves a web site. Doing one simple, functional, and good looking here on GitHub is almost trivial.

Greetings to all ...

**Comment by DBJDBJ** [comment]
I should stop closing PR's which are not merged yet ...

**Comment by DBJDBJ** [comment]
`doc` branch resurrected with some minor updates

**Comment by dbetz** [comment]
Thanks for making these improvements!

**Pull request merged**
